const yearsGrid=document.getElementById('yearsGrid');
const yearNames=['الأولى','الثانية','الثالثة','الرابعة'];
const firstYearSubjects={1:['مبادئ الاقتصاد','إدارة الأعمال','مبادئ القانون','محاسبة مالية','لغة إنجليزية (1)'],2:[]};
const textMap={
'الرئيسية':'Home','المقررات':'Courses','التقويم':'Calendar','روابط مهمة':'Important links','إنشاء جدول':'Create schedule','منصة طلابية مستقلة':'Independent student platform','مرحبًا بك في':'Welcome to','محاضراتك، سكاشنك، وجدولك في مكان واحد لطلاب قسم نظم المعلومات.':'Your lectures, sections, and schedule in one place for Information Systems students.','استعرض المقررات':'Browse courses','أنشئ جدولك':'Create your schedule','ابدأ من هنا':'Start here','اختر السنة الدراسية':'Choose the academic year','اختر السنة ثم الترم لعرض المقررات والملفات.':'Choose the year and semester to view courses and files.','اختر الترم':'Choose the semester','الترم الأول':'First semester','الترم الثاني':'Second semester','عرض مقررات الفصل الدراسي الأول':'View first-semester courses','عرض مقررات الفصل الدراسي الثاني':'View second-semester courses','قسم نظم المعلومات':'Information Systems','ترمان دراسيان ←':'Two semesters →','الفرقة الأولى':'First year','الفرقة الثانية':'Second year','الفرقة الثالثة':'Third year','الفرقة الرابعة':'Fourth year','مقررات الترم الأول':'First-semester courses','مبادئ الاقتصاد':'Principles of Economics','إدارة الأعمال':'Business Administration','مبادئ القانون':'Principles of Law','محاسبة مالية':'Financial Accounting','لغة إنجليزية (1)':'English Language (1)','فتح المادة':'Open course','سيتم إضافة محتوى هذه المادة قريبًا':'This course content will be added soon','سيتم إضافة مواد الترم الثاني قريبًا':'Second-semester courses will be added soon','المحتوى سيُضاف قريبًا':'Content will be added soon','نظّم وقتك':'Organize your time','التقويم الدراسي':'Academic calendar','لا توجد أحداث مضافة بعد':'No events have been added yet','يمكن إضافة مواعيد المحاضرات والاختبارات مستقبلًا.':'Lecture and exam dates can be added later.','وصول سريع':'Quick access','بوابة الطالب':'Student portal','المكتبة الرقمية':'Digital library','الإعلانات':'Announcements','جدولك الخاص':'Your schedule','إنشاء جدول دراسي':'Create a study schedule','أضف موادك ومواعيدها، وسيتم حفظها على جهازك.':'Add your courses and times; they will be saved on your device.','اسم المادة':'Course name','إضافة للجدول':'Add to schedule','جدولك فارغ حاليًا.':'Your schedule is currently empty.','حذف':'Delete','السبت':'Saturday','الأحد':'Sunday','الاثنين':'Monday','الثلاثاء':'Tuesday','الأربعاء':'Wednesday','الخميس':'Thursday','ذِكر':'Dhikr','منصة طلابية مستقلة لتنظيم المواد الدراسية.':'An independent student platform for organizing study materials.'};
const reverseMap=Object.fromEntries(Object.entries(textMap).map(([a,e])=>[e,a]));
let language=localStorage.getItem('obis-language')||'ar';
function translateNodeText(root=document.body){const map=language==='en'?textMap:reverseMap;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{const raw=n.nodeValue,trim=raw.trim();if(map[trim])n.nodeValue=raw.replace(trim,map[trim])});document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.getElementById('langBtn').textContent=language==='ar'?'EN':'AR';document.querySelectorAll('input[placeholder]').forEach(x=>{if(language==='en'&&textMap[x.placeholder])x.placeholder=textMap[x.placeholder];else if(language==='ar'&&reverseMap[x.placeholder])x.placeholder=reverseMap[x.placeholder]})}
function renderYears(){yearsGrid.innerHTML='';yearNames.forEach((name,i)=>yearsGrid.innerHTML+=`<button class="year-card" data-year="${i+1}"><span class="num">0${i+1}</span><span class="ico">🎓</span><h3>الفرقة ${name}</h3><p>قسم نظم المعلومات</p><b>ترمان دراسيان ←</b></button>`);document.querySelectorAll('.year-card').forEach(c=>c.onclick=()=>openYear(+c.dataset.year));if(language==='en')translateNodeText(yearsGrid)}
function openYear(y){document.getElementById('selectedYearLabel').textContent='الفرقة '+yearNames[y-1];const s=document.getElementById('subjects');s.classList.add('hidden');document.getElementById('termPanel').classList.remove('hidden');document.querySelector('.terms').classList.toggle('hidden',y!==1);if(y!==1){s.innerHTML=`<div class="empty-card"><div>🚧</div><h3>المحتوى سيُضاف قريبًا</h3></div>`;s.classList.remove('hidden')}if(language==='en')translateNodeText(document.getElementById('termPanel'));document.getElementById('termPanel').scrollIntoView({behavior:'smooth'})}
renderYears();
document.querySelectorAll('.term-card').forEach(c=>c.onclick=()=>{const t=c.dataset.term,s=document.getElementById('subjects');if(t==='2'){s.innerHTML='<div class="empty-card"><div>🚧</div><h3>سيتم إضافة مواد الترم الثاني قريبًا</h3></div>';s.classList.remove('hidden');if(language==='en')translateNodeText(s);return}s.innerHTML='<h3>مقررات الترم الأول</h3>'+firstYearSubjects[1].map(x=>`<div class="subject-row"><i>📘</i><b>${x}</b><button class="open-subject" data-subject="${x}">فتح المادة</button></div>`).join('');s.classList.remove('hidden');s.querySelectorAll('.open-subject').forEach(btn=>btn.onclick=()=>{const routes={'محاسبة مالية':'accounting','مبادئ القانون':'law','إدارة الأعمال':'business'};const subject=btn.dataset.subject;if(routes[subject])location.href=`course.html?subject=${routes[subject]}`;else alert(language==='ar'?'سيتم إضافة محتوى هذه المادة قريبًا':'This course content will be added soon')});if(language==='en')translateNodeText(s)});
document.getElementById('langBtn').onclick=()=>{language=language==='ar'?'en':'ar';localStorage.setItem('obis-language',language);location.reload()};
document.getElementById('closePanel').onclick=()=>document.getElementById('termPanel').classList.add('hidden');document.getElementById('menuBtn').onclick=()=>document.getElementById('nav').classList.toggle('open');document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('obis-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('obis-theme')==='dark')document.body.classList.add('dark');
const form=document.getElementById('scheduleForm'),list=document.getElementById('scheduleList');let items=JSON.parse(localStorage.getItem('obis-schedule')||'[]');function render(){list.innerHTML=items.length?items.map((x,i)=>`<div class="schedule-item"><span>🕒</span><b>${x.subject}</b><span>${x.day}</span><span>${x.time}</span><button class="delete" onclick="removeItem(${i})">حذف</button></div>`).join(''):'<div class="empty-card"><p>جدولك فارغ حاليًا.</p></div>';if(language==='en')translateNodeText(list)}window.removeItem=i=>{items.splice(i,1);localStorage.setItem('obis-schedule',JSON.stringify(items));render()};form.onsubmit=e=>{e.preventDefault();items.push({subject:subjectInput.value,day:dayInput.value,time:timeInput.value});localStorage.setItem('obis-schedule',JSON.stringify(items));form.reset();render()};render();document.getElementById('yearNow').textContent=new Date().getFullYear();translateNodeText();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});